CAPS_WORD_ENABLE = yes
NKRO_ENABLE = yes
COMBO_ENABLE = yes
SEND_STRING_ENABLE = yes

# Override Aurora Sweep defaults that I don't use
MOUSEKEY_ENABLE = no
ENCODER_ENABLE = no
RGB_MATRIX_ENABLE = no
OLED_ENABLE = no
BOOTMAGIC_ENABLE = no
